server:
  port: 9001

spring:
  application:
    name: minetest-fabric-application

  # datasource:
  #   url: jdbc:mysql://172.18.48.142:3306/mpc?serverTimezone=GMT%2B8
  #   username: root
  #   password: 123456
  #   driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis:
#   type-aliases-package: com.oppo.mpc.entity
#   mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2.xml

fabric:
  # wallet文件夹路径(自动创建)
  walletDirectory: wallet
  # 网络配置文件路径
  networkConfigPath: connection.json
  # 用户证书路径
  certificatePath: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
  # 用户私钥路径
  privateKeyPath: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
  # 访问的组织名
  mspid: Org1MSP
  # 用户名
  username: user1
  # 通道名字
  channelName: mychannel
  # 链码名字
  contractName: tee
#  # 链码名字
#  nft721ContractName: nft721Contract
#  # 链码名字
#  nft1155ContractName: nft1155Contract